### PR TITLE
Fix checking node exporter version by removing deprecated arguments

### LINKED ISSUE #276: Role doesn't work with Ansible 7.0.0
Hey. Looks like the role doesn't support [Ansible 7.0.0](https://github.com/ansible-community/ansible-build-data/blob/main/7/CHANGELOG-v7.rst#ansible-core-5) due to the following `shell` deprecation:

```
TASK [cloudalchemy.node_exporter : Gather currently installed node_exporter version (if any)] **********************************************************************************************
fatal: [node-1]: FAILED! => changed=false
  msg: 'Unsupported parameters for (ansible.legacy.command) module: warn. Supported parameters include: _raw_params, executable, strip_empty_ends, stdin_add_newline, creates, chdir, removes, stdin, _uses_shell, argv.'
```

### PR DESCRIPTION
**Pull request by nono-lqdn**
Closes #276

### CODE REVIEW

**Review by vol4iniche — APPROVED** [review]

**Review by rezizter — APPROVED** [review]
This fixes it for me. Is it possible to please merge to master?

**Comment by xamanu** [comment]
Same here. I'd appreciate this to be merged into `master` else the current role doesn't work with recent ansible versions anymore.

**Comment by vladget** [comment]
+1

**Comment by gatsbyz** [comment]
would be awesome if this is merged

**Comment by SuperQ** [comment]
We're deprecating this role in favor of the new [prometheus-community/ansible collection](https://github.com/prometheus-community/ansible). We're just finishing up the final release automation to Ansible Galaxy.

**Comment by SuperQ** [comment]
**This role has been deprecated in favor of a the [prometheus-community/ansible](https://github.com/prometheus-community/ansible) collection.**

**Pull request closed without merging**
