### PR TITLE
Add an option to be able to skip installation

### PR DESCRIPTION
**Pull request by smutel**
Same as https://github.com/cloudalchemy/ansible-prometheus/pull/272 but for node_exporter.

### CODE REVIEW

**Comment by paulfantom** [comment]
From CI:
>    TASK [ansible-node-exporter : Get checksum list from github] *******************
    fatal: [centos8]: FAILED! => {"msg": "The conditional check 'not node_exporter_skip_install' failed. The error was: error while evaluating conditional (not node_exporter_skip_install): 'node_exporter_skip_install' is undefined\n\nThe error appears to have been in '/home/travis/build/cloudalchemy/ansible-node-exporter/tasks/preflight.yml': line 76, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n- block:\n    - name: Get checksum list from github\n      ^ here\n"}

**Comment by paulfantom** [comment]
Again - why? In case of prometheus the explanation made sense to me, but this role is only installing node_exporter as the application itself doesn't have any configuration apart from CLI flags.

**Comment by smutel** [comment]
Except the installation of the binary, this role is doning the tasks below:
- Setup systemctl
- Setup selinux (for centos)
- Setup collectors
- ...

This option make sense (as done in prometheus role).

**Comment by paulfantom** [comment]
> Except the installation of the binary, this role is doing the tasks below:
> Setup systemctl
Setup selinux (for centos)
Setup collectors
...

All those should be done by a package/container or any other installation provider.

In the case of prometheus role, there are multiple options that couldn't be accomplished by packaging, ex. managing scrape configs, alerting, adding rules, etc. Here there are none of those.

**Comment by smutel** [comment]
This option:
  - does not affect other users
  - does not add much complexity
  - is passing the CI

This role is public so I assume that it's for the benefits of the community.
So I don't understand why you are against this option.
But you are the BOSS ...

**Comment by paulfantom** [comment]
As a maintainer of this software (who doesn't make money on it, but still responds to issues in my free time) I need a valid explanation for merging any new feature as those are adding maintenance toll. Those explanations include "benefits for the community" which are not in conflict with best practices in package creation and management.

As for your arguments:
- "does not affect other users" - that you cannot predict as this isn't implemented
- "does not add much complexity" - every feature adds complexity and it is a matter of balancing if a feature is justified. In this case, I cannot see justification since node_exporter doesn't have any configuration apart from CLI flags.	
- "is passing the CI" - it is passing CI because there are no tests for this feature.

**Pull request closed without merging**
