### PR TITLE
rewrite role to standard

### PR DESCRIPTION
**Pull request by Turgon37**

### CODE REVIEW

**Comment by Turgon37** [comment]
I'm sorry, I've choose the bad repository :(

**Comment by paulfantom** [comment]
@Turgon37 actually you have some good ideas which I should implement in this role :+1:

**Comment by paulfantom** [comment]
And you also have an error in meta/main.yml, unless you really want to name your role `role_name: nginx` :smile:

**Comment by Turgon37** [comment]
Yes, I'm fighting with typo to fix theses errors :)

**Comment by paulfantom** [comment]
A tip: remember that you cannot use `-` in role names with new ansible galaxy

**Comment by paulfantom** [comment]
Also the way you changed service file template will give you a badly rendered file.

**Comment by Turgon37** [comment]
thanks for the galaxy tips, but for the service unit file I think it's ok

```
[Unit]
Description=Prometheus Node Exporter
After=network.target

[Service]
Type=simple
User=node-exporter
Group=node-exporter
Nice=-5
ExecStart=/usr/local/bin/node_exporter \
    --collector.systemd \
    --collector.textfile.directory=/var/lib/node_exporter \
    --web.telemetry-path="/metrics" \
    --web.listen-address="10.200.57.14:9100"

SyslogIdentifier=node_exporter
Restart=always

[Install]
WantedBy=multi-user.target
```

**Comment by paulfantom** [comment]
Hmmm, strange, I used yours and it rendered it differently. I probably made some typo  :smile:

**Pull request closed without merging**
