### PR TITLE
Download and unpack node_exporter binary on remote host.

### PR DESCRIPTION
**Pull request by amirhbv**
Download and unpack node_exporter binary on remote host.

### CODE REVIEW

**Comment by paulfantom** [comment]
I am on edge with this. On one hand, this allows faster role execution in situations where remote node has a faster internet connection. On the other, it can add unnecessary downloads in large environments where role execution is always done from one deployer host. Plus in the latter scenario, it pollutes the target node instead of the deployer.
I also have concerns about disconnected environments, where target nodes don't have access to internet or this access is heavily limited.

**Comment by SuperQ** [comment]
If we did add this, we would need a switch to enable/disable it.

Part of the reason we have it this way in the first place was to avoid download from github rate limits. Especially for nodes behind NAT.

**Comment by amirhbv** [comment]
@paulfantom Yeah, you're right. My case was installing node exporter on more than 100 servers and uploading to all of them was annoying.
@SuperQ Having a switch for this is a better idea.

**Comment by dns2utf8** [comment]
I would love a switch and documentation on how to use it, because some of my servers are not allowed on the internet.

**Comment by sjpb** [comment]
the cloudalchemy prometheus role has a switch `prometheus_skip_install` to just turn off the install - which at least allows you to work around this issue (i.e. you can do the install yourself in a previous play, or bake an image with it in, or whatever)

**Comment by SuperQ** [comment]
**This role has been deprecated in favor of a the [prometheus-community/ansible](https://github.com/prometheus-community/ansible) collection.**

**Pull request closed without merging**
